### ISSUE TITLE
Questions from Ubuntu

### ISSUE THREAD

**Issue by ViciiX** [Abestanis/APython_PyToApk#2]
I tried to run the project on Ubuntu but failed, and I found out from the source that this may only work on Windows systems - is it possible to run on Ubuntu?

**Comment by Abestanis** [comment]
This should work under Ubuntu if you configure the correct paths, either via command line arguments (run `build.py -h` and `build.py [command] -h` to see all available command line arguments), or by editing the `config.cfg` file.

If you run into any problems, please let me know and reopen this issue or create a new one.
