### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by ViciiX** [Abestanis/APython_PyToApk#3]
I get an error when running this project on **Ubuntu in Termux** :
command: 
> python3 build.py apk --sourceDir examplePythonProgram
```
git version 2.37.2
[INFO ] Checking template from https://github.com/Abestanis/APython_PyApp.git... /root/ap/template/apk
正克隆到 '/root/ap/template/apk'...
remote: Enumerating objects: 338, done.
remote: Total 338 (delta 0), reused 0 (delta 0), pack-reused 338
接收对象中: 100% (338/338), 100.11 KiB | 359.00 KiB/s, 完成.
处理 delta 中: 100% (135/135), 完成.
[INFO ] Copying template to build directory...
[INFO ] Filling template...
[WARN ] Missing formatting argument appVersion, the default value provided by the template will be used
[WARN ] There was no icon specified, the default icon provided by the template will be used.
[INFO ] Cleaning examplePython sources from the template from /root/ap/build/apk/app/src/main/python...
[INFO ] Copying Python sources from /root/ap/examplePythonProgram...
[INFO ] Building apk...
[ERROR] Caught exception: [Errno 13] Permission denied: '/root/ap/build/apk/gradlew'
Traceback (most recent call last):
File "/root/ap/build.py", line 35, in executeTask
success = command.run(self.config, self.commandArgs)
File "/root/ap/src/commands/apk.py", line 203, in run
return apkBuilder.run(cmdArgs)
File "/root/ap/src/commands/apk.py", line 182, in run
apkPath = self.build(self.buildDebug)
File "/root/ap/src/commands/apk.py", line 154, in build
if not subprocess.call(args, cwd=self.apkBuildDir) == 0:
File "/usr/lib/python3.10/subprocess.py", line 345, in call
with Popen(*popenargs, **kwargs) as p:
File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/root/ap/build/apk/gradlew'
Executing command apk FAILED!

```
And when I entered that instruction the second time, the following error burst:
```
git version 2.37.2
[INFO ] Checking template from https://github.com/Abestanis/APython_PyApp.git... /root/ap/template/apk
fatal: 有歧义的参数 'origin/master'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如:
'git <命令> [<版本>...] -- [<文件>...]'
```
This contains Chinese, which looks like this after being translated into English with a translator:
```
fatal: Ambiguous parameter origin/master: Unknown version or path does not exist in the workspace.
Use -- to separate versions and paths, for example:
git command [version...] -- [file...]
```

**Comment by ViciiX** [comment]
**config.cfg**:
```
[General]
logLevel = info
avoidNetwork = false

[Paths]
buildDir = build
outputDir = output
templateDir = template
gitPath = /usr/bin/git
sdkPath = ~/android/android-sdk-linux
ndkPath = ~/android/android-ndk-r25c
#logFile = last.log

[apk]
templateGit = https://github.com/Abestanis/APython_PyApp.git
sourceDir = examplePythonProgram
buildDebug = true
#install = true

[install]
emulator = MyDevice API 19
preferEmulator = True
#device = emulator-5554
```

**Comment by Abestanis** [comment]
Can you try it again, https://github.com/Abestanis/APython_PyApp/commit/2769ace2a80b3a8b6d64b88c53610f4a2d8190d7 could have solved this. The `gradlew` script was not marked as executable, which caused the `PermissionError`.

**Comment by ViciiX** [comment]
Until then, there's one more issue waiting to be fixed - that's the issue with **git bugs** (the second issue in the first comment)
I can't run this project a second time before I delete the `template` folder in the directory

**Comment by ViciiX** [comment]
Then I deleted the `template` folder in the directory and ran the command again.
I got this error:
```
[INFO ] Copying template to build directory...
[INFO ] Filling template...
[WARN ] Missing formatting argument appVersion, the default value provided by the template will be used
[WARN ] There was no icon specified, the default icon provided by the template will be used.
[INFO ] Cleaning examplePython sources from the template from /root/ap/build/apk/app/src/main/python...
[INFO ] Copying Python sources from /root/ap/examplePythonProgram...
[INFO ] Building apk...
Starting a Gradle Daemon (subsequent builds will be faster)
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'apk'.
> Could not resolve all files for configuration ':classpath'.
    > Could not find com.android.tools.build:gradle:3.0.1.
        Searched in the following locations:
            https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
            https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
    Required by:
        project :
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 17s
[ERROR] Generating the apk failed!
Executing command apk FAILED
```

**Comment by ViciiX** [comment]
Hello?

**Comment by Abestanis** [comment]
I don't have time right now to look at this issue. I suspect it has something to to with the jcenter, I will let you know when I had time to look into it.

**Comment by ViciiX** [comment]
All right.I'm sorry for the disruption.

**Comment by Abestanis** [comment]
Hey, sorry it took a bit of time, but I found some time to look at it and fixed the problem by updating the Android Studio project of the template. Please let me know if this fixes the issue for you as well.

If you leave the target SDK version at 19, you wont be able to create a release build for now. The build system complains about Google Play require a higher target sdk version. But you can still create debug builds and I tested that it still works on an Android API 19 device.

**Comment by ViciiX** [comment]
Sorry, I've been preparing for a very important exam recently, can you remind me when this project git clone can be run directly after it is local?

**Comment by Abestanis** [comment]
I'm not sure what you mean, but if you have set `avoidNetwork` to `false` and you run the `build.py apk` command, it will update the template.

**Comment by ViciiX** [comment]
Sorry, but I don't know exactly how to do it, I just know that when I re-clone this project to the local and use the `python3 build.py apk --sourceDir examplePythonProgram` command, the following error is thrown:
```
[INFO ] Building apk...
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Python Test App'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:8.0.2.
     Required by:
         project : > com.android.application:com.android.application.gradle.plugin:8.0.2
         project : > com.android.library:com.android.library.gradle.plugin:8.0.2
      > No matching variant of com.android.tools.build:gradle:8.0.2 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0' but:
          - Variant 'apiElements' capability com.android.tools.build:gradle:8.0.2 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0')
          - Variant 'javadocElements' capability com.android.tools.build:gradle:8.0.2 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0')
          - Variant 'runtimeElements' capability com.android.tools.build:gradle:8.0.2 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0')
          - Variant 'sourcesElements' capability com.android.tools.build:gradle:8.0.2 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
[ERROR] Generating the apk failed!
Executing command apk FAILED!
```

**Comment by Abestanis** [comment]
Ah, the newer Android Studio project template requires a newer Java version. You are using Java 8, but you need to have at least Java 11 installed. See [here](https://stackoverflow.com/questions/18487406/how-do-i-tell-gradle-to-use-specific-jdk-version#answer-21212790) how to configure the JDK that the build is using.

**Comment by ViciiX** [comment]
I upgraded java to **java11** and re-run, got this error:
```
[INFO ] Building apk...
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file '/root/ap/build/apk/app/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
      Your current JDK is located in /usr/lib/jvm/java-11-openjdk-arm64
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 45s
[ERROR] Generating the apk failed!
Executing command apk FAILED!
```
then I upgraded java to **java17** and re-run, and got this different error again:
```
[INFO ] Building apk...
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)
> Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "info" is null

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
[ERROR] Generating the apk failed!
Executing command apk FAILED!
```
By the way, thanks for your patience as I'm a noob :(

**Comment by Abestanis** [comment]
> By the way, thanks for your patience

No problem at all, thank you for trying this and sorry for all the troubles, it looks like you are just getting a bit unlucky with all of these errors. 😅 I'm sure we are almost at the end though.

The error you are getting with Java 17 might be an actual error in Java: https://bugs.java.com/bugdatabase/view_bug?bug_id=8287073

According to the description there, this was fixed in Java `17.0.5`. Is our Java version newer than that and if not, could you please try updating to `17.0.5` or newer and try again?

**Comment by ViciiX** [comment]
I updated to **java18** but still getting this error
```
[INFO ] Building apk...
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)
> Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "info" is null

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
[ERROR] Generating the apk failed!
Executing command apk FAILED!
```

**Comment by Abestanis** [comment]
Which version of Java are you using exactly? Can you send the output of `java --version`, where `java` is the Java executable that is used in the build.

**Comment by Abestanis** [comment]
You can also get the Java version by executing `template/apk/gradlew --version`

I'm getting the following when executing the command (this is the JDK that comes with Android studio)
`JVM:          17.0.6 (JetBrains s.r.o. 17.0.6+10-b829.9)`

**Comment by ViciiX** [comment]
java -version
```
openjdk version "18.0.2-ea" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2-ea+9-Ubuntu-2)
OpenJDK 64-Bit Server VM (build 18.0.2-ea+9-Ubuntu-2, mixed mode, sharing)
```

template/apk/gradlew --version
```
------------------------------------------------------------
Gradle 8.0
------------------------------------------------------------

Build time:   2023-02-13 13:15:21 UTC
Revision:     62ab9b7c7f884426cf79fbedcf07658b2dbe9e97

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18.0.2-ea (Private Build 18.0.2-ea+9-Ubuntu-2)
OS:           Linux 5.4.210-qgki-g3337636e51de aarch64
```

is that so?

**Comment by Abestanis** [comment]
Yes, perfect, thank you. You are still using a Java version that is affected by the bug. On the [bug report web page](https://bugs.java.com/bugdatabase/view_bug?bug_id=8287073) you can see it says `Affected Version: 11.0.16,17.0.3,18.0.2,19` at the top. This means that any version lower and including those versions have the bug, you need a version that is newer.

This is why it works for me, because I'm using `17.0.6`, which is newer than `17.0.3`. But you are using `18.0.2`, which is not newer than `18.0.2` and therefore still affected.

If your Ubuntu does not provide a version that has the fix, maybe it would be simpler to just install [Android Studio](https://developer.android.com/studio) and use the JDK that comes with it.

**Comment by ViciiX** [comment]
I tried `Java 17.0.7`, but it still doesn't work, and since my CPU is `aarch64`, I can't seem to install Android Studio

**Comment by Abestanis** [comment]
Have you verified that gradle is using the Java `17.0.7` version by running `template/apk/gradlew --version`?

Android Studio is available for Chromebooks, which are `aarch64` based as far as I know, so it should be possible.
What device are you running this on, is it a phone?

I see some similar problems reported online ([here](https://github.com/oracle/graal/issues/4831) and [here](https://cloud.tencent.com/developer/ask/sof/106798351)) and all they say is to upgrade your JDK and to upgrade your kernel. So the last thing I can recommend is to do a full system upgrade.

But since you said you are using Ubuntu on Termux, I'm assuming you operating system underneath is actually Android/ChromeOS and it is this nesting of operating systems that is causing the trouble here. If you are running on a Chromebook, did you try building with the Terminal that comes with the Chromebook?

Alternatively, I suggest to use a different device with Windows/Linux/MacOs installed. Maybe your university/school or a friend can help you out.

**Comment by ViciiX** [comment]
Alright, it should be because I don’t have a computer, thank you for your patience

**Comment by Abestanis** [comment]
Ah, so it's not a Chromebook? Yeah, it's going to be hard to make it work in that case. I heard there are apps that try to emulate Ubuntu in a virtual machine, maybe that would work.

Alternatively I can recommend [Google Cloud services](https://cloud.google.com). You can use it for free for a pretty long time and you basically get a free Linux machine in the cloud where you can develop on.

I have one last idea to maybe make it work in Termux: Since the problem has something to do with Java interacting with `cgroup`, maybe we can just disable that interaction. Apparently it is enabled by default since Java 11. Maybe it will run if you start Java with the `-XX:-UseContainerSupport` which disables that `cgroup` integration it will work. You should be able to start the build manually like this:

```shell
$ cd template/apk
$ ./gradlew '-Dorg.gradle.jvmargs=-XX:-UseContainerSupport' assembleDebug
```

**Comment by ViciiX** [comment]
Thanks a lot, I will try it later when I have time
